# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-25 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type1', models.CharField(max_length=1000, verbose_name='标题')),
                ('addr', models.CharField(max_length=1000, verbose_name='地址')),
                ('price', models.CharField(max_length=500, verbose_name='价格')),
                ('url', models.CharField(max_length=1000, verbose_name='网址')),
            ],
            options={
                'verbose_name_plural': '房源',
                'db_table': 'location',
                'verbose_name': '房源',
            },
        ),
    ]
