# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-27 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20181026_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexgoodsbanner',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='indexpromotionbanner',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='活动图片'),
        ),
    ]
