# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-27 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20181027_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsimage',
            name='image',
            field=models.ImageField(upload_to='static/images/goods', verbose_name='图片路径'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='image',
            field=models.ImageField(upload_to='static/images/goods', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='image',
            field=models.ImageField(upload_to='static/images/type', verbose_name='商品类型图片'),
        ),
        migrations.AlterField(
            model_name='indexgoodsbanner',
            name='image',
            field=models.ImageField(upload_to='static/images', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='indexpromotionbanner',
            name='image',
            field=models.ImageField(upload_to='static/images', verbose_name='活动图片'),
        ),
    ]
